// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserMeData,
  DeleteUserMeResponses,
  DeleteUserResponses,
  LoginAccessTokenData,
  LoginAccessTokenErrors,
  LoginAccessTokenResponses,
  ReadItemData,
  ReadItemErrors,
  ReadItemResponses,
  ReadItemsData,
  ReadItemsErrors,
  ReadItemsResponses,
  ReadUserByIdData,
  ReadUserByIdErrors,
  ReadUserByIdResponses,
  ReadUserMeData,
  ReadUserMeResponses,
  ReadUsersData,
  ReadUsersErrors,
  ReadUsersResponses,
  RegisterUserData,
  RegisterUserErrors,
  RegisterUserResponses,
  TestTokenData,
  TestTokenResponses,
  UpdateItemData,
  UpdateItemErrors,
  UpdateItemResponses,
  UpdatePasswordMeData,
  UpdatePasswordMeErrors,
  UpdatePasswordMeResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserMeData,
  UpdateUserMeErrors,
  UpdateUserMeResponses,
  UpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginAccessTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginAccessTokenResponses,
    LoginAccessTokenErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/api/v1/login/access-token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Test Token
 *
 * Test access token
 */
export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<TestTokenResponses, unknown, ThrowOnError>({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/login/test-token",
    ...options,
  });

/**
 * Read Users
 *
 * Retrieve users.
 */
export const readUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadUsersResponses,
    ReadUsersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
  });

/**
 * Create User
 *
 * Create new user.
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const deleteUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteUserMeData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteUserMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  });

/**
 * Read User Me
 *
 * Get current user.
 */
export const readUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReadUserMeResponses, unknown, ThrowOnError>({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  });

/**
 * Update User Me
 *
 * Update own user.
 */
export const updateUserMe = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserMeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateUserMeResponses,
    UpdateUserMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Password Me
 *
 * Update own password.
 */
export const updatePasswordMe = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordMeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdatePasswordMeResponses,
    UpdatePasswordMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterUserResponses,
    RegisterUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/users/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 *
 * Delete a user.
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  });

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const readUserById = <ThrowOnError extends boolean = false>(
  options: Options<ReadUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ReadUserByIdResponses,
    ReadUserByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  });

/**
 * Update User
 *
 * Update a user.
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read Items
 *
 * Retrieve items.
 */
export const readItems = <ThrowOnError extends boolean = false>(
  options?: Options<ReadItemsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadItemsResponses,
    ReadItemsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/",
    ...options,
  });

/**
 * Create Item
 *
 * Create new item.
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Item
 *
 * Delete an item.
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  });

/**
 * Read Item
 *
 * Get item by ID.
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options: Options<ReadItemData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ReadItemResponses,
    ReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  });

/**
 * Update Item
 *
 * Update an item.
 */
export const updateItem = <ThrowOnError extends boolean = false>(
  options: Options<UpdateItemData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateItemResponses,
    UpdateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
