// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: string;
  /**
   * Owner Id
   */
  owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
  /**
   * Data
   */
  data: Array<ItemPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string;
};

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Id
   */
  id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Access Password
   */
  access_password?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Email
   */
  email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
  /**
   * Data
   */
  data: Array<UserPublic>;
  /**
   * Count
   */
  count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type LoginAccessTokenData = {
  body: BodyLoginLoginAccessToken;
  path?: never;
  query?: never;
  url: "/api/v1/login/access-token";
};

export type LoginAccessTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAccessTokenError =
  LoginAccessTokenErrors[keyof LoginAccessTokenErrors];

export type LoginAccessTokenResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginAccessTokenResponse =
  LoginAccessTokenResponses[keyof LoginAccessTokenResponses];

export type TestTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/login/test-token";
};

export type TestTokenResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type TestTokenResponse = TestTokenResponses[keyof TestTokenResponses];

export type ReadUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/users/";
};

export type ReadUsersErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUsersError = ReadUsersErrors[keyof ReadUsersErrors];

export type ReadUsersResponses = {
  /**
   * Successful Response
   */
  200: UsersPublic;
};

export type ReadUsersResponse = ReadUsersResponses[keyof ReadUsersResponses];

export type CreateUserData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/v1/users/";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type DeleteUserMeResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteUserMeResponse =
  DeleteUserMeResponses[keyof DeleteUserMeResponses];

export type ReadUserMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type ReadUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type UpdateUserMeData = {
  body: UserUpdateMe;
  path?: never;
  query?: never;
  url: "/api/v1/users/me";
};

export type UpdateUserMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UpdateUserMeResponse =
  UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type UpdatePasswordMeData = {
  body: UpdatePassword;
  path?: never;
  query?: never;
  url: "/api/v1/users/me/password";
};

export type UpdatePasswordMeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdatePasswordMeError =
  UpdatePasswordMeErrors[keyof UpdatePasswordMeErrors];

export type UpdatePasswordMeResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type UpdatePasswordMeResponse =
  UpdatePasswordMeResponses[keyof UpdatePasswordMeResponses];

export type RegisterUserData = {
  body: UserRegister;
  path?: never;
  query?: never;
  url: "/api/v1/users/signup";
};

export type RegisterUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type RegisterUserResponse =
  RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type DeleteUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ReadUserByIdData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type ReadUserByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUserByIdError = ReadUserByIdErrors[keyof ReadUserByIdErrors];

export type ReadUserByIdResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type ReadUserByIdResponse =
  ReadUserByIdResponses[keyof ReadUserByIdResponses];

export type UpdateUserData = {
  body: UserUpdate;
  path: {
    /**
     * User Id
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/users/{user_id}";
};

export type UpdateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserPublic;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ReadItemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/items/";
};

export type ReadItemsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemsError = ReadItemsErrors[keyof ReadItemsErrors];

export type ReadItemsResponses = {
  /**
   * Successful Response
   */
  200: ItemsPublic;
};

export type ReadItemsResponse = ReadItemsResponses[keyof ReadItemsResponses];

export type CreateItemData = {
  body: ItemCreate;
  path?: never;
  query?: never;
  url: "/api/v1/items/";
};

export type CreateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type DeleteItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteItemError = DeleteItemErrors[keyof DeleteItemErrors];

export type DeleteItemResponses = {
  /**
   * Successful Response
   */
  200: Message;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type ReadItemData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type ReadItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type ReadItemResponse = ReadItemResponses[keyof ReadItemResponses];

export type UpdateItemData = {
  body: ItemUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/api/v1/items/{id}";
};

export type UpdateItemErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
  /**
   * Successful Response
   */
  200: ItemPublic;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];
