"""
Shared Utilities Module - Common functionality across all layers.

This module provides:
- Type definitions and enums
- Global configuration
- Utility functions
- Common constants
"""

from .config import (
    DataConfig,
    EvaluationConfig,
    GlobalConfig,
    ModelConfig,
    PathConfig,
    SystemConfig,
    TrainingConfig,
    get_config,
    reset_config,
    update_config,
)
from .types import (
    ALEATORIC_SIGNALS,
    CIFAR10_CLASSES,
    COLOR_SCHEMES,
    EPISTEMIC_SIGNALS,
    GROUP_ORDER,
    SIGNAL_LABELS,
    SIGNAL_NAMES,
    BoolArray,
    CallbackProtocol,
    ConfigDict,
    DataLoaderProtocol,
    DeviceType,
    EvaluationGroup,
    ExperimentStatus,
    FloatArray,
    LabelArray,
    MetricType,
    MetricsDict,
    ModelArchitecture,
    ModelProtocol,
    NoiseType,
    PathLike,
    PredictionResult,
    SignalDict,
    SignalType,
    SplitType,
    SweepType,
    TensorLike,
    TrainingMode,
    UncertaintyMethod,
)
from .utils import (
    Timer,
    batch_to_device,
    ensure_dir,
    format_number,
    format_time,
    get_device,
    get_file_hash,
    get_logger,
    get_string_hash,
    load_json,
    load_pickle,
    load_yaml,
    retry,
    safe_execute,
    save_json,
    save_pickle,
    save_yaml,
    set_seed,
    setup_logging,
    timeit,
    to_numpy,
    to_tensor,
    truncate_string,
    validate_non_negative,
    validate_positive,
    validate_range,
)

__all__ = [
    # Config
    "DataConfig",
    "EvaluationConfig",
    "GlobalConfig",
    "ModelConfig",
    "PathConfig",
    "SystemConfig",
    "TrainingConfig",
    "get_config",
    "reset_config",
    "update_config",
    # Types
    "ALEATORIC_SIGNALS",
    "CIFAR10_CLASSES",
    "COLOR_SCHEMES",
    "EPISTEMIC_SIGNALS",
    "GROUP_ORDER",
    "SIGNAL_LABELS",
    "SIGNAL_NAMES",
    "BoolArray",
    "CallbackProtocol",
    "ConfigDict",
    "DataLoaderProtocol",
    "DeviceType",
    "EvaluationGroup",
    "ExperimentStatus",
    "FloatArray",
    "LabelArray",
    "MetricType",
    "MetricsDict",
    "ModelArchitecture",
    "ModelProtocol",
    "NoiseType",
    "PathLike",
    "PredictionResult",
    "SignalDict",
    "SignalType",
    "SplitType",
    "SweepType",
    "TensorLike",
    "TrainingMode",
    "UncertaintyMethod",
    # Utils
    "Timer",
    "batch_to_device",
    "ensure_dir",
    "format_number",
    "format_time",
    "get_device",
    "get_file_hash",
    "get_logger",
    "get_string_hash",
    "load_json",
    "load_pickle",
    "load_yaml",
    "retry",
    "safe_execute",
    "save_json",
    "save_pickle",
    "save_yaml",
    "set_seed",
    "setup_logging",
    "timeit",
    "to_numpy",
    "to_tensor",
    "truncate_string",
    "validate_non_negative",
    "validate_positive",
    "validate_range",
]

# Made with Bob