"""Shared helpers for validation notebooks and Streamlit (via re-import)."""

from __future__ import annotations

from .constants import ARCHITECTURE_STYLES, SWEEP_TO_X, UNCERTAINTY_SIGNALS
from .data_utils import (
    SweepLoadResult,
    ensure_columns,
    find_project_root,
    load_sweep_metrics,
    run_validation_experiments,
    summarize_trends,
    validate_basic_bounds,
    validate_decomposition,
    validation_dir,
)
from .method_comparison import plot_method_uncertainty_comparison
from .metric_specs import (
    ARCHITECTURE_ROW,
    AUROC_ONLY,
    MetricSpec,
    UNCERTAINTY_DECOMPOSITION,
)
from .plotting import plot_dual_axis, plot_individual_signals, plot_individual_signals_detailed
from .signals import (
    ALEATORIC_SIGNALS,
    DISENTANGLEMENT_LABELS,
    DISENTANGLEMENT_ORDER,
    EPISTEMIC_SIGNALS,
    ROW3_CANDIDATE_SIGNALS,
    ROW3_FIXED_SIGNALS,
    ROW3_FOURTH_CANDIDATES,
    SIGNAL_LABELS,
    SIGNAL_NAMES,
    aggregate_by_sweep,
    architecture_columns,
    disentanglement_label,
    format_method_architecture_mapping,
    get_method_architecture_mapping,
    get_row3_signals,
    get_top_n_signals,
    present_architectures,
    present_datasets,
    present_disentanglements,
    present_sources,
    print_method_architecture_mapping,
    resolve_x_col,
    sweep_to_auroc_type,
)

__all__ = [
    "ARCHITECTURE_STYLES",
    "SWEEP_TO_X",
    "UNCERTAINTY_SIGNALS",
    "SweepLoadResult",
    "find_project_root",
    "validation_dir",
    "run_validation_experiments",
    "load_sweep_metrics",
    "summarize_trends",
    "validate_decomposition",
    "validate_basic_bounds",
    "ensure_columns",
    "plot_individual_signals",
    "plot_individual_signals_detailed",
    "plot_dual_axis",
    "plot_method_uncertainty_comparison",
    "MetricSpec",
    "ARCHITECTURE_ROW",
    "UNCERTAINTY_DECOMPOSITION",
    "AUROC_ONLY",
    "SIGNAL_NAMES",
    "SIGNAL_LABELS",
    "EPISTEMIC_SIGNALS",
    "ALEATORIC_SIGNALS",
    "ROW3_CANDIDATE_SIGNALS",
    "ROW3_FIXED_SIGNALS",
    "ROW3_FOURTH_CANDIDATES",
    "get_row3_signals",
    "get_top_n_signals",
    "aggregate_by_sweep",
    "architecture_columns",
    "get_method_architecture_mapping",
    "print_method_architecture_mapping",
    "format_method_architecture_mapping",
    "present_architectures",
    "present_datasets",
    "present_disentanglements",
    "present_sources",
    "disentanglement_label",
    "DISENTANGLEMENT_LABELS",
    "DISENTANGLEMENT_ORDER",
    "resolve_x_col",
    "sweep_to_auroc_type",
]
